apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nodejs-mvp
  namespace: <NAME_SPACE>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nodejs
  template:
    metadata:
      labels:
        app: app-nodejs
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - name: app-nodejs-mvp
          image: '<TARGET>'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 2G
          ports:
            - containerPort: 3000
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always

