apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nodejs-mvp
  namespace: dso-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nodejs
  template:
    metadata:
      labels:
        app: app-nodejs
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - name: app-nodejs-mvp
          image: '{{ACR_INSTANCE}}.azurecr.io/ashers/app-nodejs:main'
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "200m"
          ports:
            - containerPort: 8081

