apiVersion: v1
kind: Service
metadata:
  name: app-nodejs-service
  namespace: dso-mvp
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector: 
    app: app-nodejs
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80