name: Build

on:
  push:
    branches:
      - main
      - tools_explore
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write
  packages: read

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Github Packages for NPM
        run: npm config --userconfig "${{ github.workspace }}/.npmrc" set //npm.pkg.github.com/:_authToken "${{ secrets.GITHUB_TOKEN }}"

      - name: Proxy NPM packages via Github
        run: npm config --userconfig "${{ github.workspace}}/.npmrc" set registry="https://npm.pkg.github.com/example-pipeline"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build local container
        run: podman build -t app:latest .

      - name: Grype scan
        run: grype -o sarif --file grype.sarif .

      - name: Upload Grype scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./grype.sarif
